// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FitOLS
SEXP FitOLS(const arma::colvec& y, const arma::mat& X);
RcppExport SEXP _PrattIndex_FitOLS(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(FitOLS(y, X));
    return rcpp_result_gen;
END_RCPP
}
// PrattIndexCpp
SEXP PrattIndexCpp(const arma::colvec& y, const arma::colvec& g, const arma::colvec& e);
RcppExport SEXP _PrattIndex_PrattIndexCpp(SEXP ySEXP, SEXP gSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(PrattIndexCpp(y, g, e));
    return rcpp_result_gen;
END_RCPP
}
// PrattInfluenceCpp
SEXP PrattInfluenceCpp(const arma::colvec& y, const arma::colvec& g, const arma::colvec& e);
RcppExport SEXP _PrattIndex_PrattInfluenceCpp(SEXP ySEXP, SEXP gSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(PrattInfluenceCpp(y, g, e));
    return rcpp_result_gen;
END_RCPP
}
// MatrixSqrt
SEXP MatrixSqrt(const arma::mat& S, double eps);
RcppExport SEXP _PrattIndex_MatrixSqrt(SEXP SSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(MatrixSqrt(S, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PrattIndex_FitOLS", (DL_FUNC) &_PrattIndex_FitOLS, 2},
    {"_PrattIndex_PrattIndexCpp", (DL_FUNC) &_PrattIndex_PrattIndexCpp, 3},
    {"_PrattIndex_PrattInfluenceCpp", (DL_FUNC) &_PrattIndex_PrattInfluenceCpp, 3},
    {"_PrattIndex_MatrixSqrt", (DL_FUNC) &_PrattIndex_MatrixSqrt, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PrattIndex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
