# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Marginal correlations
#'
#' Fits the standard OLS model.
#'
#' @param y (n x 1) Numeric vector.
#' @param x (n x p) Numeric matrix.
#' @return List containing the following:
#' \itemize{
#' \item{r: Correlations between y and the columns of x.}
#' \item{R: Correlations among the columns of x.}
#' }
#' @export
Corr <- function(y, x) {
    .Call(`_PrattIndex_Corr`, y, x)
}

#' Ordinary Least Squares
#'
#' Fits the standard OLS model.
#'
#' @param y (n x 1) Numeric vector.
#' @param x (n x p) Numeric matrix.
#' @param standard Standardize y and x?
#' @return List containing the following:
#' \itemize{
#' \item{beta: Regression coefficients.}
#' \item{v: Residual variance.}
#' \item{se: Standard errors.}
#' \item{z: Z-scores.}
#' \item{pval: P-values based on the chi2 distribution.}
#' }
#' @export
OLS <- function(y, x, standard = TRUE) {
    .Call(`_PrattIndex_OLS`, y, x, standard)
}

#' Pratt Index
#'
#' Calculate the Pratt index and intermediates.
#'
#' @param y (n x 1) Numeric vector.
#' @param x (n x p) Numeric matrix.
#' @param standard Standardize y and x?
#' @return List containing the following:
#' \itemize{
#' \item{beta: Regression coefficients.}
#' \item{r: Correlations between y and the columns of x.}
#' \item{R: Correlations among the columns of x.}
#' \item{pratt: Pratt indices for the columns of x.}
#' \item{var_exp: Variance in y explained by x.}
#' }
#' @export
PrattIndex <- function(y, x, standard = TRUE) {
    .Call(`_PrattIndex_PrattIndex`, y, x, standard)
}

