# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Pratt Index
#'
#' Calculate the Pratt index and intermediates.
#'
#' @param y (n x 1) Numeric vector.
#' @param x (n x p) Numeric matrix. 
#' @param Standardize y and x?
#' @return List containing the following:
#' \itemize{
#' \item{beta: (p x 1) vector of regression coefficient.}
#' \item{var_beta: (p x p) sampling variance of the regression coefficients.}
#' \item{r: (p x 1) vector of correlations between y and each column of x..}
#' \item{var_r: (p x p) sampling variance of r.}
#' \item{R: (p x p) correlation marix among the columns of x.}
#' \item{pratt: (p x 1) Pratt indices, defined as the element-wise product of beta and r.}
#' \item{var_pratt: (p x 1) sampling variance of Pratt indices.}
#' \item{resid_var: scalar residual variance of y conditional on x.}
#' \item{var_exp: scalar variance in y explained by x.}
#' }
#' @export
PrattIndex <- function(y, x, standardize = TRUE) {
    .Call(`_PrattIndex_PrattIndex`, y, x, standardize)
}

