# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ordinary Least Squares
#' 
#' Fits the standard OLS model.
#' 
#' @param y n x 1 Numeric vector.
#' @param X n x p Numeric matrix.
#' 
#' @return List containing the following:
#' \item{Beta}{Regression coefficient.}
#' \item{V}{Outcome variance.}
#' \item{Ibb}{Information matrix for beta.}
#' \item{Resid}{Outcome residuals.}
#' @export
FitOLS <- function(y, X) {
    .Call(`_PrattIndex_FitOLS`, y, X)
}

#' Pratt Index
#'
#' Calculate the Pratt index and intermediates.
#'
#' @param y (n x 1) Numeric vector.
#' @param g (n x 1) Genotype vector.
#' @param e (n x 1) Environment vector.
#' @return List containing the following:
#' \itemize{
#' \item{beta: (3 x 1) vector of regression coefficient.}
#' \item{pratt: Scalar Pratt index of the interaction term.}
#' \item{sigma2: Scalar residual variance from the joint model.}
#' \item{var_beta: (3 x 3) sampling variance of the regression coefficients.}
#' \item{var_exp: Scalar variance in y explained by x.}
#' \item{var_pratt: Scalar sampling variance of the pratt index.}
#' }
#' @export
PrattIndex <- function(y, g, e) {
    .Call(`_PrattIndex_PrattIndex`, y, g, e)
}

#' Matrix Square Root
#' @param S (p x p) numeric matrix. 
#' @param eps Scalar minimum eigenvalue.
#' @export
MatrixSqrt <- function(S, eps = 1e-8) {
    .Call(`_PrattIndex_MatrixSqrt`, S, eps)
}

